In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv("./data/Training_dataset_Original.csv")
leaderboard_data = pd.read_csv("./data/Leaderboard_dataset.csv")
test_data = pd.read_csv("./data/Evaluation_dataset.csv")

/home/ekka/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
train_data_original = train_data.copy()
leaderboard_data_original = leaderboard_data.copy()
test_data_original = test_data.copy()

In [4]:
test_data.isna().sum()

AttributeError: 'DataFrame' object has no attribute 'isna'

In [28]:
import matplotlib.pyplot as plt

In [6]:
train_data.plot(x = 'mvar1',y = 'mvar2')

In [7]:
train_data.boxplot(column = "mvar2",by = "default_ind")

In [8]:
train_data['mvar2'][train_data['default_ind'] == 0].count()

55439

In [9]:
bx = train_data.boxplot(column = 'mvar3',return_type = "both")

In [10]:
train_data['mvar3'][train_data['mvar3'] > 6.447].count()

19872

In [11]:
train_data['mvar24'].describe()

count    61098.000000
mean        69.981834
std        300.080442
min          0.000000
25%          9.892500
50%         40.440000
75%         76.540000
max      27867.400000
Name: mvar24, dtype: float64

In [12]:
train_data['mvar21'][train_data['mvar21'] > 100].count()

4460

In [13]:
train_data['mvar1'] = pd.to_numeric(train_data['mvar1'], errors='coerce')

In [14]:
train_data['mvar1'].describe()

count    76361.000000
mean      1745.971085
std         94.537617
min       1493.000000
25%       1679.000000
50%       1742.000000
75%       1810.000000
max       1950.000000
Name: mvar1, dtype: float64

In [15]:
train_data.boxplot(column = 'mvar1',by = 'default_ind')

In [16]:
train_data['mvar6'] = pd.to_numeric(train_data['mvar6'], errors='coerce')

In [17]:
train_data['mvar6'].describe()

count     61036.000000
mean       1606.702372
std        3703.654127
min           0.000000
25%          36.000000
50%         297.000000
75%        1343.250000
max      136595.000000
Name: mvar6, dtype: float64

In [18]:
for column in train_data.columns:
    if column != 'application_key':
        train_data[column] = pd.to_numeric(train_data[column], errors='coerce')

In [19]:
train_data.describe()

,application_key,mvar1,mvar2,mvar3,mvar4,mvar5,mvar6,mvar7,mvar8,mvar9,...,mvar39,mvar40,mvar41,mvar42,mvar43,mvar44,mvar45,mvar46,mvar47,default_ind
count,80000.000000,76361.000000,74447.000000,79499.000000,79499.000000,79499.00000,61036.000000,7.260600e+04,61036.00000,6.859200e+04,...,73960.000000,17443.000000,25422.000000,78099.000000,79182.000000,72255.000000,35145.000000,57211.000000,0.0,80000.000000
mean,270031.500000,1745.971085,1.105629,5.280955,0.474516,1.12472,1606.702372,1.759581e+04,6773.68666,3.409744e+04,...,0.090819,98.497452,72.096758,0.335142,6.552777,0.705285,0.070736,0.096135,NaN,0.246213
std,23094.155105,94.537617,1.645299,10.815463,1.796261,5.99545,3703.654127,4.708164e+04,10127.74526,5.337692e+04,...,0.419301,29.762399,24.442156,0.375656,6.311087,0.245879,0.287365,0.346109,NaN,0.430806
min,230032.000000,1493.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000e+00,0.00000,0.000000e+00,...,0.000000,0.014000,0.000000,0.000000,0.000000,0.060660,0.000000,0.000000,NaN,0.000000
25%,250031.750000,1679.000000,0.140100,0.000000,0.000000,0.00000,36.000000,1.756000e+03,490.00000,3.498000e+03,...,0.000000,90.689000,58.153000,0.000000,2.000000,0.515220,0.000000,0.000000,NaN,0.000000
50%,270031.500000,1742.000000,0.538900,0.300000,0.000000,0.00000,297.000000,6.967000e+03,2478.00000,1.417100e+04,...,0.000000,100.000000,78.883500,0.200000,5.000000,0.737030,0.000000,0.000000,NaN,0.000000
75%,290031.250000,1810.000000,1.445050,6.447000,0.000000,0.00000,1343.250000,1.805575e+04,9684.25000,4.385375e+04,...,0.000000,111.698000,91.639750,0.571430,10.000000,0.943475,0.000000,0.000000,NaN,0.000000
max,310031.000000,1950.000000,44.630100,286.858000,114.696000,226.52700,136595.000000,5.549600e+06,291810.00000,3.711880e+06,...,21.000000,430.300000,170.000000,2.000000,91.000000,1.000000,5.000000,19.000000,NaN,1.000000

In [164]:
train_data.isna().sum()

application_key        0
mvar1               3639
mvar2               5553
mvar3                501
mvar4                501
mvar5                501
mvar6              18964
mvar7               7394
mvar8              18964
mvar9              11408
mvar10               502
mvar11             44819
mvar12             14078
mvar13              8352
mvar14                 0
mvar15             32067
mvar16             18510
mvar17             15846
mvar18             14771
mvar19                 4
mvar20               502
mvar21             22561
mvar22             29124
mvar23             40248
mvar24             18902
mvar25              7706
mvar26             10610
mvar27             13209
mvar28               502
mvar29               502
mvar30             36417
mvar31             56218
mvar32              7706
mvar33              1751
mvar34               502
mvar35             33014
mvar36              2898
mvar37              7706
mvar38               502
mvar39              6040
mvar40             62557
mvar41             54578
mvar42              1901
mvar43               818
mvar44              7745
mvar45             44855
mvar46             22789
mvar47             80000
default_ind            0
dtype: int64

In [20]:
train_data.fillna(train_data.mean(),inplace = True)

,application_key,mvar1,mvar2,mvar3,mvar4,mvar5,mvar6,mvar7,mvar8,mvar9,...,mvar39,mvar40,mvar41,mvar42,mvar43,mvar44,mvar45,mvar46,mvar47,default_ind
0,230032,1696.000000,1.654100,0.000000,0.000000,0.00000,0.000000,6015.000000,322.00000,40369.000000,...,1.000000,73.780000,82.547000,0.086960,10.000000,0.638990,0.070736,0.000000,NaN,0
1,230033,1846.000000,0.809500,0.000000,0.000000,0.00000,102.000000,7532.000000,3171.00000,18234.000000,...,0.000000,99.129000,72.096758,0.000000,13.000000,0.638360,0.070736,0.096135,NaN,1
2,230034,1745.000000,0.400100,0.000000,0.000000,0.00000,1606.702372,2536.000000,6773.68666,34097.436013,...,0.000000,98.497452,29.290000,0.000000,1.000000,1.000000,0.070736,0.000000,NaN,1
3,230035,1739.000000,0.219300,0.000000,0.000000,0.00000,1982.000000,26440.000000,4955.00000,20316.000000,...,0.000000,96.272000,72.096758,0.153850,3.000000,0.532410,0.000000,0.000000,NaN,0
4,230036,1787.000000,0.011800,0.225000,0.000000,0.00000,5451.000000,5494.000000,5494.00000,7987.000000,...,0.000000,115.019000,72.096758,0.000000,1.000000,0.926650,0.070736,0.096135,NaN,0
5,230037,1579.000000,1.105629,3.502000,0.000000,0.00000,1606.702372,17595.807537,6773.68666,34097.436013,...,0.090819,98.497452,72.096758,1.500000,0.000000,0.705285,0.070736,0.096135,NaN,1
6,230038,1818.000000,0.400100,0.000000,0.000000,0.00000,1606.702372,1088.000000,6773.68666,1536.000000,...,0.000000,88.171000,72.096758,0.000000,2.000000,0.872240,0.070736,0.000000,NaN,1
7,230039,1745.971085,1.105629,5.280955,0.474516,1.12472,1606.702372,17595.807537,6773.68666,34097.436013,...,0.090819,98.497452,72.096758,0.335142,6.552777,0.705285,0.070736,0.096135,NaN,0
8,230040,1836.000000,0.135800,0.000000,0.000000,0.00000,347.000000,38964.000000,17828.00000,70729.000000,...,0.000000,98.497452,72.096758,0.000000,10.000000,0.898680,0.000000,0.000000,NaN,0
9,230041,1839.000000,0.198100,0.000000,0.000000,0.00000,793.000000,6131.000000,6045.00000,48959.000000,...,0.000000,98.497452,45.590000,0.088240,14.000000,0.338340,0.070736,0.000000,NaN,0
10,230042,1903.000000,0.000000,0.000000,0.000000,0.00000,22.000000,19518.000000,9910.00000,90618.000000,...,0.000000,98.497452,72.096758,0.000000,17.000000,0.806200,0.000000,0.000000,NaN,0
11,230043,1681.000000,1.588800,5.685000,3.566000,0.00000,93.000000,3554.000000,439.00000,2527.000000,...,1.000000,98.497452,72.096758,0.611110,7.000000,0.811720,0.000000,0.000000,NaN,0
12,230044,1841.000000,0.538800,0.000000,0.000000,0.00000,1487.000000,19449.000000,19449.00000,6739.000000,...,0.000000,98.497452,72.096758,0.000000,5.000000,0.980310,0.070736,0.096135,NaN,0
13,230045,1794.000000,1.968400,0.000000,0.000000,0.00000,856.000000,8609.000000,8609.00000,60545.000000,...,0.000000,98.497452,72.096758,0.000000,13.000000,0.357240,0.070736,0.000000,NaN,0
14,230046,1669.000000,3.855800,18.465000,6.292000,1.20000,1606.702372,142.000000,6773.68666,38.000000,...,0.000000,107.825000,98.664000,0.560000,11.000000,0.291690,0.070736,1.000000,NaN,0
15,230047,1583.000000,3.028400,16.325000,0.000000,0.00000,1606.702372,17595.807537,6773.68666,51450.000000,...,0.000000,98.497452,72.096758,0.323530,2.000000,0.705285,0.000000,0.096135,NaN,0
16,230048,1899.000000,0.097000,0.000000,0.000000,0.00000,1015.000000,13379.000000,13379.00000,246906.000000,...,0.000000,10.384000,72.096758,0.000000,19.000000,0.474800,0.000000,0.000000,NaN,0
17,230049,1690.000000,8.774700,10.437000,0.000000,0.00000,122.000000,623.000000,299.00000,1140.000000,...,0.000000,98.497452,72.096758,0.636360,5.000000,0.949510,0.070736,0.000000,NaN,0
18,230050,1599.000000,0.860100,1.525000,1.525000,0.00000,1606.702372,878.000000,6773.68666,34097.436013,...,1.000000,98.497452,91.175000,0.800000,0.000000,1.000000,0.070736,0.000000,NaN,1
19,230051,1859.000000,0.015500,0.368000,0.000000,0.00000,424.000000,86509.000000,12451.00000,86635.000000,...,0.000000,98.497452,72.096758,0.000000,12.000000,0.347300,0.000000,0.000000,NaN,0
20,230052,1880.000000,2.610100,0.000000,0.000000,0.00000,0.000000,19252.000000,6342.00000,59601.000000,...,0.000000,98.497452,72.497000,0.000000,14.000000,0.287080,0.070736,0.000000,NaN,0
21,230053,1852.000000,3.620100,0.000000,0.000000,0.00000,799.000000,16515.000000,16515.00000,110651.000000,...,0.000000,98.497452,72.096758,0.000000,13.000000,0.753490,0.070736,0.096135,NaN,0
22,230054,1655.000000,3.026800,14.748000,0.000000,0.00000,48.000000,48.000000,48.00000,198.000000,...,0.000000,98.497452,72.096758,1.000000,1.000000,1.000000,0.070736,0.096135,NaN,1
23,230055,1863.000000,0.040100,0.000000,0.000000,0.00000,1487.000000,4955.000000,4955.00000,22902.000000,...,0.000000,96.895000,72.096758,0.000000,12.000000,0.408530,0.070736,0.000000,NaN,0
24,230056,1753.000000,0.225100,0.000000,0.000000,0.00000,1124.000000,1124.000000,1124.00000,0.000000,...,0.000000,98.497452,72.096758,0.335142,0.000000,1.000000,0.070736,0.096135,NaN,1
25,230057,1894.000000,0.031800,0.000000,0.000000,0.00000,4655.000000,7433.000000,7433.00000,25667.000000,...,0.000000,98.497452,0.000000,0.000000,3.000000,0.994190,0.000000,0.000000,NaN,0
26,230058,1803.000000,0.399300,0.000000,0.000000,0.00000,496.000000,10505.000000,496.00000,991.000000,...,0.000000,91.752000,87.306000,0.200000,5.000000,0.752890,0.000000,0.000000,NaN,0
27,230059,1932.000000,0.327600,0.000000,0.000000,0.00000,6982.000000,21569.000000,18829.00000,187209.000000,...,0.000000,98.497452,72.096758,0.000000,11.000000,0.997100,0.000000,0.000000,NaN,0
28,230060,1714.000000,5.190400,0.770000,0.000000,0.00000,0.000000,1889.000000,595.00000,12574.000000,...,0.000000,98.497452,72.096758,0.357140,6.000000,0.850820,0.000000,0.000000,NaN,0
29,230061,1745.971085,2.045700,4.514000,0.000000,0.00000,1606.702372,17595.807537,6773.68666,34097.436013,...,0.090819,98.497452,72.096758,1.166670,0.000000,0.705285,0.070736,0.096135,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79970,310002,1834.000000,1.216400,0.000000,0.000000,0.00000,2212.000000,5244.000000,4203.00000,16743.000000,...,0.000000,98.497452,97.398000,0.000000,8.000000,0.580400,0.070736,0.000000,NaN,0
79971,310003,1729.000000,1.369600,0.000000,0.000000,0.00000,356.000000,4218.000000,1982.00000,18657.000000,...,0.000000,98.497452,83.663000,0.090910,6.000000,0.626320,0.000000,0.000000,NaN,0
79972,310004,1753.000000,5.828300,0.000000,0.000000,0.00000,180.000000,4014.000000,617.00000,3667.000000,...,0.000000,98.497452,87.094000,0.111110,9.000000,0.593640,0.070736,0.000000,NaN,0
79973,310005,1748.000000,1.963500,0.642000,0.000000,0.00000,291.000000,3469.000000,3469.00000,13131.000000,...,0.000000,98.497452,92.244000,0.440000,14.000000,0.838090,0.000000,0.000000,NaN,0
79974,310006,1771.000000,1.758800,0.000000,0.000000,0.00000,66.000000,12626.000000,6433.00000,27946.000000,...,0.000000,98.497452,40.477000,0.000000,10.000000,0.468630,0.070736,0.000000,NaN,0
79975,310007,1766.000000,0.954000,0.000000,0.000000,0.00000,1140.000000,10207.000000,10207.00000,55001.000000,...,0.000000,98.497452,72.096758,0.050000,14.000000,0.547540,0.070736,0.096135,NaN,0
79976,310008,1822.000000,0.000000,1.853000,1.853000,0.00000,2581.000000,13361.000000,5946.00000,31018.000000,...,0.000000,73.611000,44.656000,0.034480,20.000000,0.231770,0.070736,0.000000,NaN,0
79977,310009,1824.000000,0.563400,0.000000,0.000000,0.00000,3964.000000,4683.000000,4683.00000,34097.436013,...,0.000000,98.497452,72.096758,0.335142,6.552777,0.672220,0.070736,0.096135,NaN,0
79978,310010,1914.000000,0.054400,0.000000,0.000000,0.00000,3469.000000,20424.000000,20424.00000,78774.000000,...,0.000000,98.497452,72.096758,0.000000,8.000000,1.000000,0.000000,0.000000,NaN,0
79979,310011,1600.000000,2.664900,18.282000,1.078000,2.67800,0.000000,7205.000000,0.00000,956.000000,...,1.000000,132.335000,56.867000,0.552630,14.000000,0.117630,0.070736,0.000000,NaN,1
79980,310012,1822.000000,0.585100,0.000000,0.000000,0.00000,0.000000,23685.000000,23685.00000,208174.000000,...,0.000000,98.497452,72.096758,0.000000,17.000000,0.814380,0.000000,0.096135,NaN,0
79981,310013,1693.000000,0.182800,17.767000,2.024000,0.00000,114.000000,27514.000000,384.00000,2329.000000,...,0.000000,74.814000,72.096758,0.178570,5.000000,0.533400,0.070736,0.000000,NaN,0
79982,310014,1735.000000,3.170100,0.260000,0.000000,0.00000,117.000000,892.000000,117.00000,3766.000000,...,0.000000,98.497452,99.026000,0.000000,2.000000,0.967470,0.070736,0.000000,NaN,1
79983,310015,1671.000000,0.138000,0.000000,0.000000,0.00000,1606.702372,491.000000,6773.68666,34097.436013,...,0.000000,98.497452,72.096758,0.800000,2.000000,1.000000,0.070736,0.096135,NaN,0
79984,310016,1924.000000,0.122100,0.000000,0.000000,0.00000,2478.000000,266683.000000,266683.00000,405300.000000,...,0.000000,98.497452,70.799000,0.000000,13.000000,0.753220,0.000000,0.000000,NaN,0
79985,310017,1670.000000,0.034700,9.836000,0.000000,0.00000,212.000000,7848.000000,491.00000,29785.000000,...,0.000000,98.497452,78.700000,0.136360,10.000000,0.857710,0.070736,0.000000,NaN,0
79986,310018,1901.000000,0.178200,0.000000,0.000000,0.00000,4955.000000,21753.000000,12673.00000,70293.000000,...,0.000000,98.497452,61.301000,0.000000,10.000000,0.863560,0.000000,0.000000,NaN,0
79987,310019,1835.000000,0.537200,0.000000,0.000000,0.00000,0.000000,29723.000000,3964.00000,66770.000000,...,0.000000,98.497452,72.096758,0.000000,9.000000,0.416850,0.000000,0.000000,NaN,0
79988,310020,1927.000000,0.041000,0.000000,0.000000,0.00000,22000.000000,30046.000000,24165.00000,75019.000000,...,0.000000,98.497452,19.444000,0.000000,7.000000,0.537500,0.000000,0.000000,NaN,0
79989,310021,1745.971085,0.145100,0.000000,0.000000,0.00000,1606.702372,17595.807537,6773.68666,34097.436013,...,0.090819,98.497452,72.096758,1.500000,0.000000,0.705285,0.070736,0.096135,NaN,0
79990,310022,1941.000000,0.483400,0.000000,0.000000,0.00000,10846.000000,52806.000000,35478.00000,136461.000000,...,0.000000,98.497452,72.096758,0.058820,8.000000,0.841700,0.000000,0.000000,NaN,0
79991,310023,1899.000000,1.105629,0.000000,0.000000,0.00000,7310.000000,14519.000000,14519.00000,5252.000000,...,0.000000,98.497452,72.096758,0.000000,3.000000,0.446150,0.070736,0.096135,NaN,0
79992,310024,1761.000000,2.099900,0.000000,0.000000,0.00000,47.000000,13477.000000,1814.00000,9320.000000,...,0.000000,98.497452,72.096758,0.125000,5.000000,0.736400,0.000000,0.000000,NaN,1
79993,310025,1700.000000,0.383100,0.000000,0.000000,0.00000,344.000000,344.000000,344.00000,991.000000,...,0.000000,98.497452,72.096758,0.666670,2.000000,0.973740,0.000000,0.000000,NaN,1
79994,310026,1910.000000,0.000000,0.000000,0.000000,0.00000,4955.000000,47306.000000,47306.00000,88124.000000,...,0.000000,98.497452,72.096758,0.000000,4.000000,0.798670,0.070736,0.096135,NaN,0
79995,310027,1736.000000,2.174000,0.000000,0.000000,0.00000,11.000000,4248.000000,1577.00000,13379.000000,...,0.000000,98.497452,78.378000,0.000000,4.000000,0.438290,0.070736,0.000000,NaN,0
79996,310028,1724.000000,0.000000,1.108000,0.768000,0.00000,1606.702372,64041.000000,6773.68666,10926.000000,...,0.000000,98.497452,38.325000,0.166670,14.000000,0.579310,0.000000,0.000000,NaN,0
79997,310029,1605.000000,0.290100,11.561000,0.937000,2.97600,1606.702372,2277.000000,6773.68666,3964.000000,...,2.000000,101.850000,93.142000,0.500000,4.000000,0.420690,0.070736,0.000000,NaN,1
79998,310030,1780.000000,1.187400,0.000000,0.000000,0.00000,0.000000,6356.000000,4802.00000,3206.000000,...,0.000000,98.497452,77.022000,0.060610,9.000000,0.532510,0.070736,0.000000,NaN,0
79999,310031,1727.000000,1.928800,1.441000,0.000000,0.00000,0.000000,25773.000000,2869.00000,132985.000000,...,0.000000,32.400000,72.096758,0.071430,12.000000,0.684820,0.000000,0.000000,NaN,1

In [30]:
train_data.isna().sum()

AttributeError: 'DataFrame' object has no attribute 'isna'

In [31]:
pd.__version__

'0.20.1'

In [22]:
train_data['mvar47'] = pd.get_dummies(train_data_original['mvar47'])

In [23]:
x_train = train_data.loc[:,'mvar1':'mvar47']
y_train = train_data['default_ind']

In [24]:
leaderboard_data.describe()

,application_key,mvar2,mvar3,mvar4,mvar5,mvar14,mvar21,mvar22,mvar23,mvar24,mvar33,mvar44
count,25000.000000,23294.000000,24842.000000,24842.000000,24842.000000,2.500000e+04,18106.000000,15919.000000,12359.000000,19223.000000,24461.000000,22538.000000
mean,362552.500000,1.118127,5.243267,0.463290,1.080183,1.523549e+05,57.885791,4427.876770,4270.918441,72.500520,6.920566,0.702558
std,7217.022701,1.658707,10.605688,1.688155,5.813250,6.337980e+06,35.344775,3813.637964,3774.419701,305.673992,7.655343,0.246612
min,350053.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.117000,0.000000,0.000000,0.000000,0.083300,0.072760
25%,356302.750000,0.142725,0.000000,0.000000,0.000000,4.261300e+04,27.244750,750.845000,532.705000,10.345000,1.166700,0.509132
50%,362552.500000,0.542400,0.286000,0.000000,0.000000,7.234300e+04,59.569500,3978.570000,3707.500000,41.220000,3.833300,0.732740
75%,368802.250000,1.469375,6.480000,0.000000,0.000000,1.238750e+05,86.366500,7523.980000,7405.470000,76.250000,10.500000,0.942372
max,375052.000000,31.018100,167.740000,21.245200,156.878000,9.910000e+08,565.800000,99800.000000,41737.500000,22621.130000,76.500000,1.000000

In [25]:
for column in leaderboard_data.columns:
    if column != 'application_key':
        leaderboard_data[column] = pd.to_numeric(leaderboard_data[column], errors='coerce')

In [26]:
leaderboard_data.describe()

,application_key,mvar1,mvar2,mvar3,mvar4,mvar5,mvar6,mvar7,mvar8,mvar9,...,mvar38,mvar39,mvar40,mvar41,mvar42,mvar43,mvar44,mvar45,mvar46,mvar47
count,25000.000000,23850.000000,23294.000000,24842.000000,24842.000000,24842.000000,19193.000000,2.269400e+04,19193.000000,21523.000000,...,24842.000000,23078.000000,5458.000000,7748.000000,24367.000000,24723.000000,22538.000000,11027.000000,17851.000000,0.0
mean,362552.500000,1746.901551,1.118127,5.243267,0.463290,1.080183,1624.069192,1.775037e+04,6753.202313,33825.554662,...,4.251349,0.089912,98.491140,71.990942,0.331992,6.546091,0.702558,0.071280,0.092712,NaN
std,7217.022701,94.088195,1.658707,10.605688,1.688155,5.813250,3588.247900,5.485979e+04,10133.583639,51781.414456,...,3.870975,0.444250,30.488996,24.806054,0.374753,6.260583,0.246612,0.302654,0.321896,NaN
min,350053.000000,1477.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.018000,0.000000,0.000000,0.000000,0.072760,0.000000,0.000000,NaN
25%,356302.750000,1680.000000,0.142725,0.000000,0.000000,0.000000,36.000000,1.701000e+03,494.000000,3518.000000,...,2.000000,0.000000,91.338250,58.179500,0.000000,2.000000,0.509132,0.000000,0.000000,NaN
50%,362552.500000,1742.000000,0.542400,0.286000,0.000000,0.000000,297.000000,7.011500e+03,2503.000000,14072.000000,...,3.000000,0.000000,100.000000,79.123000,0.200000,5.000000,0.732740,0.000000,0.000000,NaN
75%,368802.250000,1811.000000,1.469375,6.480000,0.000000,0.000000,1371.000000,1.803575e+04,9595.000000,43009.500000,...,6.000000,0.000000,112.237500,91.666000,0.561950,10.000000,0.942372,0.000000,0.000000,NaN
max,375052.000000,1950.000000,31.018100,167.740000,21.245200,156.878000,59192.000000,5.637108e+06,223123.000000,840658.000000,...,73.000000,20.000000,631.360000,182.111000,2.000000,63.000000,1.000000,7.000000,3.000000,NaN

In [27]:
leaderboard_data['mvar47'] = pd.get_dummies(leaderboard_data_original['mvar47'])

In [28]:
leaderboard_data.fillna(leaderboard_data.mean(),inplace = True)

,application_key,mvar1,mvar2,mvar3,mvar4,mvar5,mvar6,mvar7,mvar8,mvar9,...,mvar38,mvar39,mvar40,mvar41,mvar42,mvar43,mvar44,mvar45,mvar46,mvar47
0,350053,1753.0,0.500100,0.000,0.0000,0.000,206.000000,19179.000000,206.000000,14221.000000,...,1.0,0.000000,98.49114,20.551000,0.42105,3.0,0.856610,0.07128,0.000000,0
1,350054,1894.0,1.970100,0.000,0.0000,0.000,297.000000,19820.000000,19820.000000,176895.000000,...,3.0,0.000000,98.49114,63.047000,0.00000,15.0,0.943910,0.00000,0.000000,1
2,350055,1774.0,0.171800,0.000,0.0000,0.000,197.000000,2563.000000,877.000000,8869.000000,...,1.0,0.000000,98.49114,83.797000,0.33333,3.0,0.764670,0.00000,0.000000,1
3,350056,1586.0,0.112300,5.299,0.0000,0.000,1624.069192,17750.368864,6753.202313,33825.554662,...,1.0,0.089912,98.49114,71.990942,1.50000,0.0,0.702558,0.07128,0.092712,1
4,350057,1832.0,1.444200,0.000,0.0000,0.000,179.000000,7577.000000,179.000000,21059.000000,...,3.0,0.000000,96.05200,66.665000,0.00000,23.0,0.791900,0.00000,0.000000,0
5,350058,1838.0,0.054400,0.241,0.0000,0.000,882.000000,14039.000000,10976.000000,278941.000000,...,4.0,0.000000,98.49114,77.780000,0.00000,21.0,0.924620,0.00000,0.000000,0
6,350059,1743.0,1.075300,0.272,0.0000,0.000,397.000000,16141.000000,3568.000000,69482.000000,...,6.0,0.000000,98.49114,67.159000,0.00000,14.0,0.713470,0.00000,0.000000,0
7,350060,1935.0,0.560100,0.000,0.0000,0.000,496.000000,44919.000000,17115.000000,124814.000000,...,9.0,0.000000,98.49114,71.990942,0.00000,15.0,0.924030,0.00000,0.000000,0
8,350061,1885.0,0.081100,0.000,0.0000,0.000,7369.000000,19264.000000,19264.000000,59956.000000,...,1.0,0.000000,98.49114,71.990942,0.00000,5.0,0.897600,0.00000,0.092712,0
9,350062,1730.0,0.744400,0.000,0.0000,0.000,0.000000,2103.000000,582.000000,16429.000000,...,9.0,0.000000,98.49114,71.990942,0.05882,14.0,0.405290,0.07128,0.000000,1
10,350063,1731.0,0.509700,0.000,0.0000,0.000,2433.000000,8673.000000,8673.000000,6739.000000,...,2.0,0.000000,98.49114,71.990942,0.23529,1.0,0.642420,0.00000,0.092712,1
11,350064,1755.0,0.301300,0.000,0.0000,0.000,261.000000,4051.000000,261.000000,297.000000,...,3.0,0.000000,98.49114,71.990942,0.33333,2.0,0.991420,0.07128,0.000000,1
12,350065,1739.0,2.290900,0.000,0.0000,0.000,0.000000,7620.000000,7620.000000,64983.000000,...,11.0,0.000000,98.49114,95.000000,0.05882,16.0,0.441670,0.07128,0.000000,1
13,350066,1562.0,0.000000,34.611,3.7845,0.000,1624.069192,18.000000,6753.202313,198.000000,...,7.0,1.000000,124.91000,99.934000,0.87500,1.0,0.845920,1.00000,1.000000,1
14,350067,1798.0,5.082500,0.000,0.0000,0.000,259.000000,3359.000000,2973.000000,22099.000000,...,5.0,0.000000,98.49114,76.881000,0.05882,13.0,0.433650,0.00000,0.000000,1
15,350068,1684.0,1.547900,1.338,0.0000,0.000,1624.069192,17750.368864,6753.202313,33825.554662,...,3.0,0.089912,98.49114,71.990942,1.50000,0.0,0.702558,0.07128,0.092712,1
16,350069,1789.0,0.000000,1.428,0.0000,0.000,2478.000000,13874.000000,13874.000000,98011.000000,...,4.0,0.000000,98.49114,71.990942,0.05000,13.0,0.512310,0.07128,0.092712,0
17,350070,1862.0,0.240100,0.000,0.0000,0.000,1487.000000,12310.000000,3964.000000,7928.000000,...,6.0,0.000000,98.49114,77.419000,0.00000,7.0,0.566850,0.00000,0.000000,1
18,350071,1767.0,0.300100,1.514,0.0000,0.000,991.000000,2478.000000,2478.000000,8790.000000,...,1.0,0.000000,98.49114,71.990942,0.10000,3.0,0.702558,0.07128,0.092712,1
19,350072,1802.0,0.636400,0.000,0.0000,0.000,96.000000,18759.000000,10905.000000,51037.000000,...,3.0,0.000000,98.49114,58.972000,0.00000,9.0,0.594090,0.00000,0.000000,1
20,350073,1780.0,1.955900,0.000,0.0000,0.000,191.000000,12525.000000,12525.000000,18932.000000,...,7.0,0.000000,98.49114,100.000000,0.00000,7.0,0.927520,0.00000,0.000000,1
21,350074,1714.0,2.266400,0.000,0.0000,0.000,31.000000,1671.000000,57.000000,396.000000,...,6.0,0.000000,98.49114,91.666000,0.37500,5.0,0.348360,0.07128,0.000000,1
22,350075,1923.0,0.088000,0.000,0.0000,0.000,5946.000000,53893.000000,24739.000000,128435.000000,...,2.0,0.000000,98.49114,90.429000,0.00000,9.0,0.885540,0.00000,0.000000,1
23,350076,1743.0,1.720800,2.295,0.0000,0.000,159.000000,3621.000000,2323.000000,9018.000000,...,8.0,0.000000,98.49114,82.323000,0.10000,9.0,0.594420,0.07128,0.000000,1
24,350077,1700.0,1.660500,0.000,0.0000,0.000,0.000000,1037.000000,46.000000,892.000000,...,5.0,0.000000,98.49114,71.990942,0.20000,5.0,0.948260,0.07128,0.000000,0
25,350078,1922.0,1.118127,0.000,0.0000,0.000,4524.000000,15530.000000,14819.000000,116154.000000,...,3.0,0.000000,98.49114,71.990942,0.00000,12.0,0.915500,0.00000,0.000000,0
26,350079,1777.0,0.412000,0.000,0.0000,0.000,369.000000,6201.000000,6201.000000,66477.000000,...,12.0,0.000000,98.49114,71.990942,0.03846,23.0,0.151590,0.07128,0.092712,1
27,350080,1811.0,0.911700,0.410,0.0000,0.410,297.000000,27717.000000,9815.000000,110001.000000,...,3.0,0.000000,98.49114,74.996000,0.00000,15.0,0.566710,0.00000,0.000000,1
28,350081,1658.0,2.382900,37.127,10.3678,0.000,0.000000,396.000000,0.000000,6566.000000,...,14.0,0.000000,98.49114,71.990942,0.57692,8.0,0.353390,0.07128,2.000000,1
29,350082,1827.0,0.280100,0.000,0.0000,0.000,678.000000,1189.000000,1189.000000,892.000000,...,3.0,0.000000,98.49114,71.990942,0.00000,2.0,1.000000,0.07128,0.092712,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24970,375023,1734.0,0.927900,0.520,0.0000,0.000,256.000000,11643.000000,1524.000000,16748.000000,...,7.0,0.000000,98.49114,71.990942,0.00000,10.0,0.380780,0.07128,0.000000,0
24971,375024,1849.0,1.830500,0.000,0.0000,0.000,2251.000000,33275.000000,7505.000000,44843.000000,...,2.0,0.000000,98.49114,91.701000,0.00000,4.0,0.921110,0.00000,0.000000,0
24972,375025,1739.0,1.525100,2.727,0.0000,2.727,8.000000,2129.000000,720.000000,5896.000000,...,6.0,0.000000,109.25100,94.127000,0.36842,12.0,0.529030,0.07128,0.000000,1
24973,375026,1642.0,0.000000,3.353,1.2114,0.000,1624.069192,6290.000000,6753.202313,33825.554662,...,1.0,0.000000,98.49114,37.890000,0.83333,0.0,1.000000,0.07128,0.000000,1
24974,375027,1709.0,3.680100,7.583,3.1371,0.000,297.000000,8132.000000,297.000000,1041.000000,...,32.0,0.000000,81.02900,71.990942,0.59459,11.0,0.426800,0.07128,2.000000,1
24975,375028,1890.0,0.000000,0.000,0.0000,0.000,1982.000000,15162.000000,15162.000000,68181.000000,...,2.0,0.000000,98.04300,55.197000,0.00000,15.0,0.271430,0.07128,0.000000,1
24976,375029,1727.0,1.844800,15.181,0.0000,0.000,2234.000000,2754.000000,2234.000000,2676.000000,...,4.0,0.000000,98.49114,71.990942,0.66667,5.0,0.878900,0.00000,0.000000,1
24977,375030,1789.0,1.299400,0.000,0.0000,0.000,364.000000,17838.000000,17838.000000,8424.000000,...,5.0,0.000000,109.30700,75.052000,0.15385,8.0,0.696940,0.00000,0.000000,0
24978,375031,1706.0,0.499700,0.000,0.0000,0.000,98.000000,297.000000,98.000000,546.000000,...,7.0,0.000000,98.49114,71.990942,0.66667,4.0,1.000000,0.07128,0.000000,1
24979,375032,1638.0,4.680200,16.751,2.6642,0.000,1624.069192,7937.000000,6753.202313,3032.000000,...,3.0,1.000000,102.70900,13.882000,0.50000,4.0,0.726400,0.07128,0.000000,1
24980,375033,1855.0,1.996500,0.000,0.0000,0.000,350.000000,30203.000000,22656.000000,168999.000000,...,2.0,0.000000,98.49114,71.990942,0.00000,12.0,0.741060,0.00000,0.092712,0
24981,375034,1790.0,0.205000,0.000,0.0000,0.000,237.000000,18018.000000,13297.000000,3914.000000,...,5.0,0.000000,98.49114,71.990942,0.20000,2.0,0.415820,0.07128,0.000000,1
24982,375035,1546.0,0.349100,50.803,4.2695,0.000,1624.069192,17750.368864,6753.202313,3330.000000,...,8.0,0.000000,98.49114,71.990942,0.70370,2.0,1.000000,1.00000,1.000000,1
24983,375036,1777.0,3.962900,0.968,0.0000,0.000,14.000000,23707.000000,23707.000000,33432.000000,...,12.0,0.000000,98.49114,80.934000,0.04000,15.0,0.647520,0.07128,0.000000,0
24984,375037,1943.0,1.118127,0.000,0.0000,0.000,0.000000,24775.000000,24775.000000,80772.000000,...,0.0,0.000000,98.49114,71.990942,0.00000,6.0,0.970680,0.00000,0.092712,1
24985,375038,1691.0,0.166300,1.979,0.0000,0.000,0.000000,9591.000000,2627.000000,46903.000000,...,5.0,0.000000,84.80100,63.855000,0.03448,14.0,0.434410,0.07128,0.000000,1
24986,375039,1681.0,0.173900,9.006,0.0000,6.568,0.000000,3004.000000,2251.000000,6818.000000,...,1.0,1.000000,96.30900,71.990942,0.71429,2.0,0.889080,0.00000,0.000000,1
24987,375040,1723.0,1.057000,0.285,0.0000,0.000,248.000000,28479.000000,28479.000000,16352.000000,...,7.0,0.000000,98.49114,71.990942,0.00000,6.0,0.723440,0.07128,0.000000,1
24988,375041,1693.0,1.214500,0.000,0.0000,0.000,18.000000,100.000000,100.000000,991.000000,...,3.0,0.000000,98.49114,71.990942,0.00000,3.0,0.366190,0.07128,0.092712,1
24989,375042,1592.0,6.480500,5.250,0.0000,1.204,1624.069192,0.000000,6753.202313,33825.554662,...,3.0,0.000000,100.00000,71.990942,1.00000,1.0,0.506490,0.07128,0.092712,1
24990,375043,1641.0,0.660100,8.614,0.0000,0.000,1624.069192,0.000000,6753.202313,33825.554662,...,3.0,0.000000,100.00000,71.990942,1.00000,1.0,1.000000,0.07128,0.092712,0
24991,375044,1740.0,0.390100,4.322,0.0000,0.000,490.000000,29460.000000,9449.000000,42047.000000,...,3.0,0.000000,98.49114,71.990942,0.20000,4.0,0.889570,1.00000,0.000000,0
24992,375045,1651.0,2.490900,1.335,0.9108,0.000,4.000000,3163.000000,4.000000,1982.000000,...,10.0,0.000000,98.49114,82.382000,0.61538,3.0,0.937450,0.07128,0.000000,0
24993,375046,1729.0,1.360100,0.218,0.0000,0.000,0.000000,5675.000000,167.000000,15071.000000,...,5.0,0.000000,98.49114,71.990942,0.23810,13.0,0.718660,0.07128,0.000000,1
24994,375047,1730.0,1.670100,5.554,0.0000,0.000,104.000000,5692.000000,496.000000,4410.000000,...,5.0,0.000000,98.49114,79.485000,0.30769,4.0,0.933120,0.07128,0.000000,1
24995,375048,1715.0,12.000200,0.000,0.0000,0.000,1624.069192,991.000000,6753.202313,8751.000000,...,1.0,0.000000,98.49114,71.990942,0.07692,4.0,0.702558,0.07128,0.000000,1
24996,375049,1800.0,0.055100,0.000,0.0000,0.000,5946.000000,14867.000000,9613.000000,46490.000000,...,4.0,0.000000,98.49114,71.990942,0.05882,8.0,0.998590,0.00000,0.000000,0
24997,375050,1686.0,1.330100,2.025,0.0000,2.025,1624.069192,0.000000,6753.202313,4582.000000,...,0.0,0.000000,124.17100,71.990942,0.30000,2.0,0.775190,0.07128,0.092712,0
24998,375051,1826.0,1.118127,0.428,0.0000,0.000,3568.000000,26277.000000,9058.000000,72739.000000,...,2.0,0.000000,98.49114,50.119000,0.03333,11.0,0.403430,0.07128,0.000000,1
24999,375052,1916.0,0.139400,0.000,0.0000,0.000,18889.000000,18889.000000,18889.000000,28343.000000,...,0.0,0.000000,98.49114,71.990942,0.00000,5.0,0.996630,0.00000,0.000000,1

In [32]:
x_test = leaderboard_data.loc[:,'mvar1':]

In [33]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [34]:
pred = clf.predict_proba(x_test)

In [35]:
pred = pd.DataFrame(pred)
pred['application_key'] = leaderboard_data['application_key']

In [36]:
pred.shape

(25000, 3)

In [37]:
pred = pred.sort_values(by = 0,kind = 'mergesort',ascending = False)

In [38]:
cols = pred.columns.tolist()
cols = cols[-1:] + cols[:-1]
pred = pred[cols]

In [39]:
pred = pred.loc[:,'application_key':]

In [40]:
submit = pred['application_key'][:10000]

In [41]:
submit = pd.DataFrame(submit)

submit

In [42]:
submit[0] = 0

In [183]:
submit.to_csv('flabbergasted_IITGuwahati_34.csv',header = False, index = False)

AttributeError: 'Series' object has no attribute 'columns'